import { AdminProduct, AdminCategory } from '@/types/admin';

export const MOCK_CATEGORIES: AdminCategory[] = [
    { id: 'cat-001', name: 'Herramientas Eléctricas', slug: 'herramientas-electricas', created_at: new Date().toISOString() },
    { id: 'cat-002', name: 'Equipos Industriales', slug: 'equipos-industriales', created_at: new Date().toISOString() },
    { id: 'cat-003', name: 'Seguridad', slug: 'seguridad-industrial', created_at: new Date().toISOString() },
    { id: 'cat-004', name: 'Maquinaria Pesada', slug: 'maquinaria-pesada', created_at: new Date().toISOString() },
];

export const MOCK_LOCAL_PRODUCTS: AdminProduct[] = [
    {
        id: 'prod-001',
        name: 'Taladro Percutor Industrial XRP',
        slug: 'taladro-percutor-xrp',
        category_id: 'cat-001',
        category: { name: 'Herramientas Eléctricas' },
        price: 299.99,
        description: 'Taladro percutor de 20V MAX* sin escobillas. Rendimiento profesional para perforación en concreto y mampostería.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 45,
        sku: 'TLD-XRP-2024',
        image_url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-002',
        name: 'Amoladora Angular Inalámbrica',
        slug: 'amoladora-angular-inalambrica',
        category_id: 'cat-001',
        category: { name: 'Herramientas Eléctricas' },
        price: 189.50,
        description: 'Amoladora angular de 4-1/2 pulgadas y batería de litio. Diseño compacto y motor de alto rendimiento.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 12,
        sku: 'AML-IND-001',
        image_url: 'https://images.unsplash.com/photo-1588825852503-b097af4c6e7a?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-003',
        name: 'Sierra Circular de Mesa Profesional',
        slug: 'sierra-circular-mesa',
        category_id: 'cat-002',
        category: { name: 'Equipos Industriales' },
        price: 850.00,
        description: 'Sierra de banco motor de 15 amperios, capacidad de corte profundo. Incluye soporte rodante y discos de precisión.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 8,
        sku: 'SRR-C15A',
        image_url: 'https://images.unsplash.com/photo-1621644053912-eeed4fa7848f?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-004',
        name: 'Nivel Láser Autonivelante 360°',
        slug: 'nivel-laser-360',
        category_id: 'cat-001',
        category: { name: 'Herramientas Eléctricas' },
        price: 245.00,
        description: 'Nivel láser verde de 3 líneas cruzadas. Autonivelación inteligente, hasta 50 metros de rango visible para construcción en interiores.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 30,
        sku: 'NVL-LSR-360',
        image_url: 'https://images.unsplash.com/photo-1596768393529-57e3353ae405?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-005',
        name: 'Generador Eléctrico Inverter 4000W',
        slug: 'generador-inverter-4000w',
        category_id: 'cat-002',
        category: { name: 'Equipos Industriales' },
        price: 1200.00,
        description: 'Generador a gasolina ultra silencioso. Ideal para obras en construcción remotas o suministro energético de emergencia.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 4,
        sku: 'GEN-INV-4K',
        image_url: 'https://images.unsplash.com/photo-1610486801977-88ab10cd9ffc?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-006',
        name: 'Casco de Seguridad Smart-Tech',
        slug: 'casco-smart-tech',
        category_id: 'cat-003',
        category: { name: 'Seguridad' },
        price: 125.00,
        description: 'Casco de fibra de carbono resistente a impactos clase E con chip NFC para registro de ingreso de empleados a obra.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 120,
        sku: 'CSC-SMT-001',
        image_url: 'https://images.unsplash.com/photo-1541888031383-e18e385203fa?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-007',
        name: 'Arnés de Caza de Cuerpo Completo',
        slug: 'arnes-cuerpo-completo',
        category_id: 'cat-003',
        category: { name: 'Seguridad' },
        price: 89.90,
        description: 'Arnés de seguridad anticaídas, anillos D ergonómicos, correas ajustables. Carga hasta 150 kg en el sitio de trabajo.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 55,
        sku: 'ARN-CX-5',
        image_url: 'https://images.unsplash.com/photo-1580228045934-2edaf3b9e4a8?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-008',
        name: 'Compresor de Aire Portátil V-Twin',
        slug: 'compresor-aire-twin',
        category_id: 'cat-002',
        category: { name: 'Equipos Industriales' },
        price: 499.00,
        description: 'Compresor sin aceite de 20 galones, presión de 150 PSI. Motores gemelos en V para recarga super rápida y constante.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 10,
        sku: 'CMP-V20G',
        image_url: 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-009',
        name: 'Montacargas Hidráulico Pallet Jack',
        slug: 'montacargas-pallet-jack',
        category_id: 'cat-004',
        category: { name: 'Maquinaria Pesada' },
        price: 340.00,
        description: 'Elevador de pallets manual. Capacidad de 5,500 lbs, marco de acero soldado reforzado para logística en almacenes grandes.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 18,
        sku: 'MNT-P5500',
        image_url: 'https://images.unsplash.com/photo-1623048550186-0925e0a6e0c6?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-010',
        name: 'Lijadora Roto-Orbital de 5"',
        slug: 'lijadora-roto-orbital',
        category_id: 'cat-001',
        category: { name: 'Herramientas Eléctricas' },
        price: 135.50,
        description: 'Velocidad variable para acabado impecable. Extracción de polvo superior gracias a la turbina interna.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 42,
        sku: 'LIJ-R05',
        image_url: 'https://images.unsplash.com/photo-1647466858284-90407727a20c?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-011',
        name: 'Chaleco Reflectante Grado 2',
        slug: 'chaleco-reflectante-g2',
        category_id: 'cat-003',
        category: { name: 'Seguridad' },
        price: 15.00,
        description: 'Malla transpirable 100% poliéster. Bandas de 2 pulgadas retro-reflectantes frontales y traseras.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 300,
        sku: 'CHL-REF-G2',
        image_url: 'https://images.unsplash.com/photo-1602418579979-d5eeddc49f50?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-012',
        name: 'Carretilla Elevadora Diésel 3.0T',
        slug: 'carretilla-elevadora-3t',
        category_id: 'cat-004',
        category: { name: 'Maquinaria Pesada' },
        price: 18500.00,
        description: 'Motor Isuzu industrial de inyección directa. Tracción neumática, ideal para terreno irregular.',
        is_active: false, // Inactivo demo
        created_at: new Date().toISOString(),
        stock_quantity: 0,
        sku: 'CARR-VD-30L',
        image_url: 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-013',
        name: 'Llave de Impacto de 1/2"',
        slug: 'llave-impacto-1-2',
        category_id: 'cat-001',
        category: { name: 'Herramientas Eléctricas' },
        price: 215.00,
        description: 'Torque masivo para despegue rápido de tuercas. Carcasa de composite liviana para máxima agilidad en faena.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 26,
        sku: 'LLAV-IMP-02',
        image_url: 'https://images.unsplash.com/photo-1628399564268-d05de29a39ca?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-014',
        name: 'Extintor de Polvo Químico ABC (10kg)',
        slug: 'extintor-pqs-10kg',
        category_id: 'cat-003',
        category: { name: 'Seguridad' },
        price: 45.99,
        description: 'Agente extintor multipropósito al 90% fosfato monoamónico. Cilindro resistente, manguera reforzada y manómetro certificado.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 80,
        sku: 'EXT-ABC-10K',
        image_url: 'https://images.unsplash.com/photo-1563216839-4cb50325dd85?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-015',
        name: 'Polipasto de Cadena Tonelero',
        slug: 'polipasto-cadena',
        category_id: 'cat-002',
        category: { name: 'Equipos Industriales' },
        price: 520.00,
        description: 'Levante eléctrico de cadena hasta 2000kg, doble velocidad, suspensión de gancho o carro. Cumple normativa ASME.',
        is_active: true,
        created_at: new Date().toISOString(),
        stock_quantity: 3,
        sku: 'POL-CAD-2T',
        image_url: 'https://images.unsplash.com/photo-1616447823528-76ad06b3a0cc?q=80&w=600&auto=format&fit=crop',
        created_by: 'admin-demo',
    }
];
