import { AdminProduct, AdminCategory } from '@/types/admin';

export const MOCK_CATEGORIES: AdminCategory[] = [
    {
        id: 'cat-ev-01',
        name: 'Propulsión Eléctrica',
        slug: 'propulsion-electrica',
        image_url: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&q=80&w=200'
    },
    {
        id: 'cat-ind-01',
        name: 'Componentes Industriales',
        slug: 'componentes-industriales',
        image_url: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=200'
    },
    {
        id: 'cat-bat-01',
        name: 'Almacenamiento Energético',
        slug: 'almacenamiento-energetico',
        image_url: 'https://images.unsplash.com/photo-1568444438385-eee3366edc6d?auto=format&fit=crop&q=80&w=200'
    },
    {
        id: 'cat-sen-01',
        name: 'Sensores y Control',
        slug: 'sensores-y-control',
        image_url: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=200'
    },
];

export const MOCK_LOCAL_PRODUCTS: any[] = [
    {
        id: 'prod-ev-001',
        name: 'Módulo de Propulsión EV Industrial v4',
        slug: 'modulo-propulsion-ev-industrial',
        brand: 'OSART POWER',
        category_id: 'cat-ev-01',
        category: { id: 'cat-ev-01', name: 'Propulsión Eléctrica' },
        price: 4500.00,
        original_price: 5200.00,
        discount_tag: '13% OFF',
        rating: 4.9,
        reviews_count: 86,
        description: 'Motor síncrono de imanes permanentes con inversor integrado de 150kW. Diseñado para vehículos de carga pesada y maquinaria autónoma.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 12,
        sku: 'EV-PROP-X150',
        image_url: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        free_shipping: true,
    },
    {
        id: 'prod-bat-001',
        name: 'Celda de Energía Lithium-Ion Core-X',
        slug: 'celda-energia-lithium-ion',
        brand: 'NEXUS ENERGY',
        category_id: 'cat-bat-01',
        category: { id: 'cat-bat-01', name: 'Almacenamiento Energético' },
        price: 850.00,
        rating: 4.8,
        reviews_count: 142,
        description: 'Módulo de batería de alta densidad con sistema de gestión (BMS) avanzado. Capacidad de descarga rápida para arranques de alta potencia.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 45,
        sku: 'BAT-CORE-LIT',
        image_url: 'https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?auto=format&fit=crop&q=80&w=800',

        created_by: 'admin-demo',
        arrive_today: true,
    },
    {
        id: 'prod-ind-001',
        name: 'Inversor de Frecuencia Variable UltraPower',
        slug: 'inversor-frecuencia-variable',
        brand: 'SIEMENS REF',
        category_id: 'cat-ind-01',
        category: { id: 'cat-ind-01', name: 'Componentes Industriales' },
        price: 1200.00,
        original_price: 1450.00,
        discount_tag: 'HOT',
        rating: 4.7,
        reviews_count: 56,
        description: 'Controlador de motor de precisión para líneas de ensamblaje automatizadas. Soporta protocolos industriales avanzados.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 20,
        sku: 'VFD-ULT-800',
        image_url: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&q=80&w=800',

        created_by: 'admin-demo',
    },
    {
        id: 'prod-sen-001',
        name: 'Matriz de Sensores Ultrasónicos de Precisión',
        slug: 'matriz-sensores-ultrasonicos',
        brand: 'SENSE-TECH',
        category_id: 'cat-sen-01',
        category: { id: 'cat-sen-01', name: 'Sensores y Control' },
        price: 340.00,
        rating: 4.9,
        reviews_count: 31,
        description: 'Sistema de detección de proximidad con precisión milimétrica. Ideal para evasión de obstáculos en flotas de AGV.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 110,
        sku: 'SEN-ULTZ-99',
        image_url: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-ind-002',
        name: 'Actuador Robótico de 6 Ejes Industrial',
        slug: 'actuador-robotico-industrial',
        brand: 'BOLT ARMS',
        category_id: 'cat-ind-01',
        category: { id: 'cat-ind-01', name: 'Componentes Industriales' },
        price: 12500.00,
        rating: 5.0,
        reviews_count: 14,
        description: 'Brazo articulado para tareas de soldadura y Pick & Place de alta velocidad. Estándar de protección IP67.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 5,
        sku: 'ROB-ACT-AX6',
        image_url: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        free_shipping: true,
    },
    {
        id: 'prod-ev-002',
        name: 'Interfaz de Carga Rápida EV v3.2',
        slug: 'interfaz-carga-rapida-ev',
        brand: 'OSART CHARGE',
        category_id: 'cat-ev-01',
        category: { id: 'cat-ev-01', name: 'Propulsión Eléctrica' },
        price: 550.00,
        original_price: 600.00,
        rating: 4.6,
        reviews_count: 92,
        description: 'Conector de carga compatible con CCS2. Soporta hasta 350kW para reducir tiempos muertos en estaciones de servicio.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 60,
        sku: 'EV-CHG-CCS2',
        image_url: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-ind-003',
        name: 'Husillo Industrial de Titanio Reforzado',
        slug: 'husillo-industrial-titanio',
        brand: 'TITAN MACHINA',
        category_id: 'cat-ind-01',
        category: { id: 'cat-ind-01', name: 'Componentes Industriales' },
        price: 2100.00,
        rating: 4.8,
        reviews_count: 23,
        description: 'Componente de alta resistencia para fresadoras CNC. Tratamiento térmico para durabilidad extrema en condiciones severas.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 15,
        sku: 'IND-SPN-TIT',
        image_url: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-sen-002',
        name: 'Placa de Control AI Edge Industrial',
        slug: 'placa-control-ai-edge',
        brand: 'LOGIC CORE',
        category_id: 'cat-sen-01',
        category: { id: 'cat-sen-01', name: 'Sensores y Control' },
        price: 890.00,
        rating: 4.9,
        reviews_count: 67,
        description: 'Unidad de procesamiento local para algoritmos de visión artificial y mantenimiento predictivo en el borde.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 35,
        sku: 'AI-LOG-PLC',
        image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        arrive_today: true,
    },
    {
        id: 'prod-ind-004',
        name: 'Transductor de Presión Hidráulica Pro',
        slug: 'transductor-presion-hidraulica',
        brand: 'FLOW CONTROL',
        category_id: 'cat-ind-01',
        category: { id: 'cat-ind-01', name: 'Componentes Industriales' },
        price: 185.00,
        rating: 4.7,
        reviews_count: 48,
        description: 'Sensor de presión de alta gama para sistemas hidráulicos masivos. Salida digital de alta precisión para control remoto.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 150,
        sku: 'HYD-PRS-TPH',
        image_url: 'https://images.unsplash.com/photo-1591405351990-4726e33df584?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-ind-005',
        name: 'Carcasa de Seguridad de Fibra Compuesta',
        slug: 'carcasa-seguridad-fibra-compuesta',
        brand: 'OSART SHIELD',
        category_id: 'cat-ind-01',
        category: { id: 'cat-ind-01', name: 'Componentes Industriales' },
        price: 320.00,
        rating: 4.5,
        reviews_count: 19,
        description: 'Protección ligera y ultra-resistente para componentes electrónicos expuestos a entornos químicos o térmicos.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 200,
        sku: 'SHLD-FIB-COMP',
        image_url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    }
];

export const MOCK_ORDERS: any[] = [
    {
        id: 'ORD-99281',
        user_id: 'demo-user',
        status: 'delivered',
        payment_status: 'paid',
        total: 5350.00,
        subtotal: 5350.00,
        shipping: 0,
        shipping_address: 'Planta Industrial Norte, Quilicura, Chile',
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        items: [
            {
                id: 'ITM-001',
                product_id: 'prod-ev-001',
                quantity: 1,
                unit_price: 4500.00,
                product: MOCK_LOCAL_PRODUCTS[0]
            },
            {
                id: 'ITM-002',
                product_id: 'prod-bat-001',
                quantity: 1,
                unit_price: 850.00,
                product: MOCK_LOCAL_PRODUCTS[1]
            }
        ]
    }
];
