import { AdminProduct, AdminCategory } from '@/types/admin';

export const MOCK_CATEGORIES: AdminCategory[] = [
    {
        id: 'cat-001',
        name: 'Herramientas Eléctricas',
        slug: 'herramientas-electricas',
        image_url: 'https://images.unsplash.com/photo-1504148455328-c39695715583?auto=format&fit=crop&q=80&w=200'
    },
    {
        id: 'cat-002',
        name: 'Equipos Industriales',
        slug: 'equipos-industriales',
        image_url: 'https://images.unsplash.com/photo-1541829081-21443a60783a?auto=format&fit=crop&q=80&w=200'
    },
    {
        id: 'cat-003',
        name: 'Seguridad',
        slug: 'seguridad-industrial',
        image_url: 'https://images.unsplash.com/photo-1589330694653-9118c7c93de8?auto=format&fit=crop&q=80&w=200'
    },
    {
        id: 'cat-004',
        name: 'Maquinaria Pesada',
        slug: 'maquinaria-pesada',
        image_url: 'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&q=80&w=200'
    },
];

export const MOCK_LOCAL_PRODUCTS: any[] = [
    {
        id: 'prod-001',
        name: 'Taladro Percutor Industrial XRP',
        slug: 'taladro-percutor-industrial-xrp',
        brand: 'DEWALT',
        category_id: 'cat-001',
        category: { id: 'cat-001', name: 'Herramientas Eléctricas' },
        price: 299.99,
        original_price: 349.99,
        discount_tag: '14% OFF',
        rating: 4.8,
        reviews_count: 124,
        description: 'Taladro percutor de 20V MAX* sin escobillas. Rendimiento profesional para perforación en concreto y mampostería.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 45,
        sku: 'TLD-XRP-2024',
        image_url: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        free_shipping: true,
    },
    {
        id: 'prod-002',
        name: 'Amoladora Angular Inalámbrica',
        slug: 'amoladora-angular-inal-mbrica',
        brand: 'MAKITA',
        category_id: 'cat-001',
        category: { id: 'cat-001', name: 'Herramientas Eléctricas' },
        price: 189.50,
        original_price: 210.00,
        rating: 4.5,
        reviews_count: 89,
        description: 'Amoladora angular de 4-1/2 pulgadas y batería de litio. Diseño compacto y motor de alto rendimiento.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 12,
        sku: 'AML-IND-001',
        image_url: 'https://images.unsplash.com/photo-1540103359326-367d12f6227c?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        arrive_today: true,
    },
    {
        id: 'prod-003',
        name: 'Sierra Circular de Mesa Profesional',
        slug: 'sierra-circular-de-mesa-profesional',
        brand: 'BOSCH',
        category_id: 'cat-002',
        category: { id: 'cat-002', name: 'Equipos Industriales' },
        price: 850.00,
        rating: 4.9,
        reviews_count: 56,
        description: 'Sierra de banco motor de 15 amperios, capacidad de corte profundo. Incluye soporte rodante y discos de precisión.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 8,
        sku: 'SRR-C15A',
        image_url: 'https://images.unsplash.com/photo-1530124566582-a61a1275b16f?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        free_shipping: true,
    },
    {
        id: 'prod-004',
        name: 'Nivel Láser Autonivelante 360°',
        slug: 'nivel-l-ser-autonivelante-360',
        brand: 'STANLEY',
        category_id: 'cat-001',
        category: { id: 'cat-001', name: 'Herramientas Eléctricas' },
        price: 245.00,
        original_price: 289.00,
        discount_tag: '15% OFF',
        rating: 4.7,
        reviews_count: 42,
        description: 'Nivel láser verde de 3 líneas cruzadas. Autonivelación inteligente, hasta 50 metros de rango visible para construcción en interiores.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 30,
        sku: 'NVL-LSR-360',
        image_url: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
        arrive_today: true,
    },
    {
        id: 'prod-005',
        name: 'Generador Eléctrico Inverter 4000W',
        slug: 'generador-el-ctrico-inverter-4000w',
        brand: 'HONDA',
        category_id: 'cat-002',
        category: { id: 'cat-002', name: 'Equipos Industriales' },
        price: 1200.00,
        rating: 5.0,
        reviews_count: 12,
        description: 'Generador a gasolina ultra silencioso. Ideal para obras en construcción remotas o suministro energético de emergencia.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 4,
        sku: 'GEN-INV-4K',
        image_url: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-006',
        name: 'Casco de Seguridad Smart-Tech',
        slug: 'casco-de-seguridad-smart-tech',
        category_id: 'cat-003',
        category: { id: 'cat-003', name: 'Seguridad' },
        price: 125.00,
        description: 'Casco de fibra de carbono resistente a impactos clase E con chip NFC para registro de ingreso de empleados a obra.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 120,
        sku: 'CSC-SMT-001',
        image_url: 'https://images.unsplash.com/photo-1589939705384-5185138a04b9?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-007',
        name: 'Arnés de Caza de Cuerpo Completo',
        slug: 'arn-s-de-caza-de-cuerpo-completo',
        category_id: 'cat-003',
        category: { id: 'cat-003', name: 'Seguridad' },
        price: 89.90,
        description: 'Arnés de seguridad anticaídas, anillos D ergonómicos, correas ajustables. Carga hasta 150 kg en el sitio de trabajo.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 55,
        sku: 'ARN-CX-5',
        image_url: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ec4?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-008',
        name: 'Compresor de Aire Portátil V-Twin',
        slug: 'compresor-de-aire-port-til-v-twin',
        category_id: 'cat-002',
        category: { id: 'cat-002', name: 'Equipos Industriales' },
        price: 499.00,
        description: 'Compresor sin aceite de 20 galones, presión de 150 PSI. Motores gemelos en V para recarga super rápida y constante.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 10,
        sku: 'CMP-V20G',
        image_url: 'https://images.unsplash.com/photo-1581092921461-7d2fb88a8d79?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-009',
        name: 'Montacargas Hidráulico Pallet Jack',
        slug: 'montacargas-hidr-ulico-pallet-jack',
        category_id: 'cat-004',
        category: { id: 'cat-004', name: 'Maquinaria Pesada' },
        price: 340.00,
        description: 'Elevador de pallets manual. Capacidad de 5,500 lbs, marco de acero soldado reforzado para logística en almacenes grandes.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 18,
        sku: 'MNT-P5500',
        image_url: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-010',
        name: 'Lijadora Roto-Orbital de 5"',
        slug: 'lijadora-roto-orbital-de-5',
        category_id: 'cat-001',
        category: { id: 'cat-001', name: 'Herramientas Eléctricas' },
        price: 135.50,
        description: 'Velocidad variable para acabado impecable. Extracción de polvo superior gracias a la turbina interna.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 42,
        sku: 'LIJ-R05',
        image_url: 'https://images.unsplash.com/photo-1581092334651-ddf26d9a1930?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-011',
        name: 'Chaleco Reflectante Grado 2',
        slug: 'chaleco-reflectante-grado-2',
        category_id: 'cat-003',
        category: { id: 'cat-003', name: 'Seguridad' },
        price: 15.00,
        description: 'Malla transpirable 100% poliéster. Bandas de 2 pulgadas retro-reflectantes frontales y traseras.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 300,
        sku: 'CHL-REF-G2',
        image_url: 'https://images.unsplash.com/photo-1591954840042-76bc5d54b18c?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-012',
        name: 'Carretilla Elevadora Diésel 3.0T',
        slug: 'carretilla-elevadora-di-sel-3-0t',
        category_id: 'cat-004',
        category: { id: 'cat-004', name: 'Maquinaria Pesada' },
        price: 18500.00,
        description: 'Motor Isuzu industrial de inyección directa. Tracción neumática, ideal para terreno irregular.',
        is_active: false,
        createdAt: new Date().toISOString(),
        stock_quantity: 0,
        sku: 'CARR-VD-30L',
        image_url: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-013',
        name: 'Llave de Impacto de 1/2"',
        slug: 'llave-de-impacto-de-1-2',
        category_id: 'cat-001',
        category: { id: 'cat-001', name: 'Herramientas Eléctricas' },
        price: 215.00,
        description: 'Torque masivo para despegue rápido de tuercas. Carcasa de composite liviana para máxima agilidad en faena.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 26,
        sku: 'LLAV-IMP-02',
        image_url: 'https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-014',
        name: 'Extintor de Polvo Químico ABC (10kg)',
        slug: 'extintor-de-polvo-qu-mico-abc-10kg',
        category_id: 'cat-003',
        category: { id: 'cat-003', name: 'Seguridad' },
        price: 45.99,
        description: 'Agente extintor multipropósito al 90% fosfato monoamónico. Cilindro resistente, manguera reforzada y manómetro certificado.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 80,
        sku: 'EXT-ABC-10K',
        image_url: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    },
    {
        id: 'prod-015',
        name: 'Polipasto de Cadena Tonelero',
        slug: 'polipasto-de-cadena-tonelero',
        category_id: 'cat-002',
        category: { id: 'cat-002', name: 'Equipos Industriales' },
        price: 520.00,
        description: 'Levante eléctrico de cadena hasta 2000kg, doble velocidad, suspensión de gancho o carro. Cumple normativa ASME.',
        is_active: true,
        createdAt: new Date().toISOString(),
        stock_quantity: 3,
        sku: 'POL-CAD-2T',
        image_url: 'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&q=80&w=800',
        created_by: 'admin-demo',
    }
];
export const MOCK_ORDERS: any[] = [
    {
        id: 'ORD-99281',
        user_id: 'demo-user',
        status: 'delivered',
        payment_status: 'paid',
        total: 489.49,
        subtotal: 469.99,
        shipping: 19.50,
        shipping_address: 'Av. Industrial 404, Santiago, Chile',
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        items: [
            {
                id: 'ITM-001',
                product_id: 'prod-001',
                quantity: 1,
                unit_price: 299.99,
                product: MOCK_LOCAL_PRODUCTS[0]
            },
            {
                id: 'ITM-002',
                product_id: 'prod-002',
                quantity: 1,
                unit_price: 189.50,
                product: MOCK_LOCAL_PRODUCTS[1]
            }
        ]
    },
    {
        id: 'ORD-10293',
        user_id: 'demo-user',
        status: 'processing',
        payment_status: 'paid',
        total: 850.00,
        subtotal: 850.00,
        shipping: 0,
        shipping_address: 'Calle Técnica 101, Valparaíso, Chile',
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        items: [
            {
                id: 'ITM-003',
                product_id: 'prod-003',
                quantity: 1,
                unit_price: 850.00,
                product: MOCK_LOCAL_PRODUCTS[2]
            }
        ]
    }
];
